blog/forms.py
"""
Author: Josh and Andrew
Description: This module defines a Flask form class named 'RecipeForm' used for capturing recipe details.
"""
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import StringField, SubmitField, FileField, FloatField
from wtforms.validators import DataRequired, NumberRange, Regexp, ValidationError
from flask_uploads import IMAGES, UploadSet, configure_uploads
from app import app
import re

# sets all the image file types to the variable images
images = UploadSet('images', IMAGES)
configure_uploads(app, images)


# validation for the price field using regex (1, 1.99, 1.00, not 1.9)
def validate_data(form, field):
    if not field.data:
        return
    pattern = re.compile(r"^\d+(\.\d{2})?$")
    if not pattern.match(field.data):
        raise ValidationError("Price must be in the proper format e.g. (1, 1.99, 10.00)")


# form class for uploading a recipe, all form fields must be filled in
class RecipeForm(FlaskForm):
    title = StringField(validators=[DataRequired()])
    recipe = StringField(validators=[DataRequired()])
    ingredients = StringField(validators=[DataRequired()])
    # only allows IMAGES to be uploaded
    image = FileField(validators=[
        FileAllowed(images, "only images are allowed"),
        FileRequired("file field should not be empty")
    ])
    price = StringField(validators=[DataRequired(), validate_data])
    submit = SubmitField()


# form class for editing a recipe, doesn't require all form fields to be filled
class EditRecipeForm(FlaskForm):
    title = StringField()
    recipe = StringField()
    ingredients = StringField()
    image = FileField(validators=[
        FileAllowed(images, "only images are allowed")])
    price = StringField(validators=[validate_data])
    submit = SubmitField()

blog/views.py
"""
Author: Josh and Andrew
Description: This module defines a Flask blueprint for a blog feature. It includes routes and views for creating,
 displaying, and accessing recipes.
"""
import notifications
from blog.forms import RecipeForm, images, EditRecipeForm
from models import Post
from flask import Blueprint, render_template, url_for, send_from_directory
from app import db, app, requires_roles
from flask_login import login_required, current_user

blog_blueprint = Blueprint('blog', __name__, template_folder='templates')


# Send a file from within a directory using send_file.
@app.route("/images/images/<filename>")
def get_file(filename):
    return send_from_directory("images/images", filename)


# blog function for handling blog form inputs
@blog_blueprint.route('/blog', methods=['GET', 'POST'])
@login_required
@requires_roles('user', 'admin')
def blog():
    form = RecipeForm()
    if form.validate_on_submit():

        # receives image and saves to app default file path
        image_name = images.save(form.image.data)
        # gets url for image to save in the database
        image_url = url_for("get_file", filename=image_name)

        new_post = Post(user_id=current_user.id,
                        title=form.title.data,
                        recipe=form.recipe.data,
                        ingredients=form.ingredients.data,
                        image=image_url,
                        price=form.price.data)

        # add the new recipe to the database
        db.session.add(new_post)
        db.session.commit()

        # sends email notification of new blog post to all users signed up
        notifications.send_emails()

        return render_template('/blog/blog.html', form=form, file_url=image_url)

    return render_template('/blog/blog.html', form=form)


# gets all recipe posts from database and passes them to blog_home to display
@blog_blueprint.route('/blog_home', methods=['GET','POST'])
def blog_home():
    recipes = Post.query.all()
    order_by = "recent"
    if recipes:
        return render_template('blog/blog_home.html', recipes=recipes, order_by=order_by)

    return render_template('blog/blog_home.html')


# sorts recipe Posts by either amount of views or most recent and renders a new blog_home
@blog_blueprint.route('/order_recipes/<order>', methods=['GET','POST'])
def order_recipes(order):
    if order == "views":
        recipes = Post.query.order_by(Post.views.desc()).all()
        return render_template('blog/blog_home.html', recipes=recipes, order_by=order)
    if order == "recent":
        recipes = Post.query.order_by(Post.post_id.desc()).all()
        return render_template('blog/blog_home.html', recipes=recipes, order_by=order)


# gets the clicked on recipe from the database to display it fully in recipe.html
@blog_blueprint.route('/recipe/<recipe_id>', methods=['GET','POST'])
def recipe(recipe_id):
    recipe = Post.query.filter_by(post_id=recipe_id).first()
    if recipe:
        # increments views as it's been clicked on
        views = recipe.views
        views += 1
        recipe.views = views
        db.session.commit()
        return render_template('blog/recipe.html', recipe=recipe)

    return render_template('blog/recipe.html')


# deletes the recipe when delete is clicked, can only be done by admins or by the posts author
@login_required
@requires_roles('user', 'admin')
@blog_blueprint.route('/delete_recipe/<recipe_id>', methods=['GET','POST'])
def delete_recipe(recipe_id):
    recipe = Post.query.filter_by(post_id=recipe_id).first()
    if recipe:
        db.session.delete(recipe)
        db.session.commit()
        recipes = Post.query.all()

        return render_template('blog/blog_home.html', recipes=recipes)

    return render_template('blog/recipe.html')


# Allows authors or admins to edit their posts.
@login_required
@requires_roles('user', 'admin')
@blog_blueprint.route('/edit_recipe/<recipe_id>',  methods=['GET','POST'])
def edit_recipe(recipe_id):
    form = EditRecipeForm()
    # gets recipe to edit
    recipe = Post.query.filter_by(post_id=recipe_id).first()

    # if statements allow users to edit as much or as little as they want
    if form.validate_on_submit():
        if form.image.data:
            image_name = images.save(form.image.data)
            image_url = url_for("get_file", filename=image_name)
            recipe.image = image_url

        if form.title.data:
            recipe.title = form.title.data

        if form.recipe.data:
            recipe.recipe = form.recipe.data

        if form.ingredients.data:
            recipe.ingredients = form.ingredients.data

        if form.price.data:
            recipe.price = form.price.data

        db.session.commit()

        return render_template('blog/recipe.html', recipe=recipe)

    if recipe:
        return render_template('blog/edit_recipe.html', recipe=recipe, form=form)

    return render_template('blog/blog_home.html')

templates/blog/blog.html
<!--Authors: Josh + Andrew -->

{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <img class="background-img" src="{{ url_for('static', filename='images/greenbackground.jpg') }}">
    </div>
    {% if current_user.is_authenticated %}
        <div class="column is-5 is-offset-4">
        {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="notification is-danger">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                {% endwith %}
                <form method="POST" enctype="multipart/form-data">
                    <div class="field">
                        {{ form.csrf_token }}
                        <div class="control">
                            {{ form.title(class="input", placeholder="Title") }}
                            {% for error in form.title.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.recipe(class="textarea", placeholder="Recipe") }}
                            {% for error in form.recipe.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.ingredients(class="textarea", placeholder="Ingredients") }}
                            {% for error in form.ingredients.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            {{ form.price(class="input", placeholder="Price") }}
                            {% for error in form.price.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-auto">
                            {{ form.image(class="form-control")}}
                            {% for error in form.image.errors %}
                                    {{ error }}
                                {% endfor %}
                        </div>
                    </div>
                    <div>
                        {{ form.submit(class="button is-info is-centered") }}
                    </div>
                    {% if file_url %}
                        <div class="mt-5">
                            <img src="{{file_url}}" style="width: 400px;">
                            <a>submitted</a>
                            <a href="{{url_for('blog.blog_home')}}" >Go back to home page</a>
                        </div>
                    {% endif %}
                </form>
        </div>
    {% endif %}


{% endblock %}

templates/blog/blog_home.html
<!--Authors: Josh + Andrew -->

{% extends 'base.html' %}

{% block content %}
    <div class="container is-fluid">
        <img class="background-img" src="{{ url_for('static', filename='images/greenbackground.jpg') }}">
    </div>
    <div class="container-recipe-title">
        <h1 class="caption">Recipe Blog</h1>
        {% if current_user.is_authenticated %}
        <div class="container-recipe-post">
            <a href="{{url_for('blog.blog')}}" class="button is-primary">Post a recipe</a>
        </div>
        {% endif %}
    </div>

    <div class="featured-recipes">
        <h3 class="title is-3">Featured Recipes</h3>
    </div>


    <div class="dropdown is-fluid">
        <span class="tag is-rounded">
            <label for="dropdown-checkbox"><strong>Order By: {{ order_by }}</strong></label>
            <input type="checkbox" id="dropdown-checkbox">
            <div class="dropdown-content">
                <a href="/order_recipes/{{ "views" }}">Views</a>
                <a href="/order_recipes/{{ "recent" }}">Recent</a>
            </div>
        </span>
    </div>


    {% if recipes %}
        <div class="container">
          <div class="columns is-multiline">
            {% for recipe in recipes %}
            <div class="column">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-4by3">
                    <img src="{{ recipe.image }}" alt='RECIPE IMAGE NOT FOUND'>
                  </figure>
                </div>
                <div class="card-content">
                  <p class="title is-4">{{ recipe.title }}</p>
                  <div class="content">
                    <p><strong>£</strong> {{ recipe.price }}</p>
                  </div>
                </div>
                <footer class="card-footer">
                  <a href="/recipe/{{ recipe.post_id }}" class="card-footer-item">View Recipe</a>
                </footer>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
    {% endif %}

{% endblock %}

templates/blog/edit_recipe.html
<!--Authors: Josh + Andrew -->

{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <img class="background-img" src="{{ url_for('static', filename='images/greenbackground.jpg') }}">
    </div>
    {% if current_user.is_authenticated %}
        <div class="column is-5 is-offset-4">
        {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="notification is-danger">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                {% endwith %}
                <form method="POST" enctype="multipart/form-data">
                    <div class="field">
                        {{ form.csrf_token() }}
                        <div class="control">
                            <a>Change recipe title from "{{ recipe.title }}"</a>
                            {{ form.title(class="input", placeholder="Title") }}
                            {% for error in form.title.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <a>Change recipe from "{{ recipe.recipe }}"</a>
                            {{ form.recipe(class="input", placeholder="Recipe") }}
                            {% for error in form.recipe.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <a>Change recipe ingredients from "{{ recipe.ingredients }}"</a>
                            {{ form.ingredients(class="input", placeholder="Ingredients") }}
                            {% for error in form.ingredients.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <a>Change recipe price from "£{{ recipe.price }}"</a>
                            {{ form.price(class="input", placeholder="Price") }}
                            {% for error in form.price.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-auto">
                            <a>Change recipe image</a>
                            {{ form.image(class="form-control")}}
                            {% for error in form.image.errors %}
                                    {{ error }}
                                {% endfor %}
                        </div>
                    </div>
                    <div>
                        {{ form.submit(class="button is-info is-centered") }}
                    </div>
                </form>
        </div>
    {% endif %}


{% endblock %}

templates/blog/recipe.html
<!--Authors: Josh + Andrew -->

{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <img class="background-img" src="{{ url_for('static', filename='images/greenbackground.jpg') }}">
    </div>
    {% if recipe %}
        <div class="card is-fluid">
            <div class="card-image">
                <figure class="image is-3by1">
                    <img src="{{ recipe.image }}" alt="Placeholder image">
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">{{ recipe.title }}</p>
                        <p class="subtitle is-6">Cost: £{{ recipe.price }}</p>
                    </div>
                </div>

                <div class="content">
                    <p class="subtitle is-5">Recipe</p>
                    {{ recipe.recipe }}
                    <p class="subtitle is-5">Ingredients</p>
                    {{ recipe.ingredients }}

                </div>
                <footer class="card-footer">
                    {% if current_user.is_authenticated and (current_user.id == recipe.user_id or current_user.role == 'admin')%}
                        <a href="/delete_recipe/{{ recipe.post_id }}" class="card-footer-item">Delete</a>
                        <a href="/edit_recipe/{{ recipe.post_id }}" class="card-footer-item">Edit</a>
                    {% endif %}
                </footer>
            </div>
        </div>

    {% endif %}

{% endblock %}