admin/views.py
"""
Author: Josh and Shaikha
Description: This module defines a Flask blueprint for an admin feature.
The 'admin' blueprint includes routes and views for managing administrative tasks.
"""
from flask import Blueprint, render_template
from flask_login import login_required
from models import User
from app import requires_roles


admin_blueprint = Blueprint('admin', __name__, template_folder='templates')


@admin_blueprint.route('/admin')
@login_required
@requires_roles('admin')
def admin():
    return render_template('admin/admin.html')


# view all registered users
@admin_blueprint.route('/view_all_users', methods=['POST'])
@login_required
@requires_roles('admin')
def view_all_users():
    current_users = User.query.filter_by(role='user').all()
    return render_template('admin/admin.html', name="PLACEHOLDER FOR FIRSTNAME", current_users=current_users)


@admin_blueprint.route('/logs', methods=['POST'])
@login_required
@requires_roles('admin')
def logs():
    with open("blog.log", "r") as f:
        content = f.read().splitlines()[-20:]

    return render_template('admin/admin.html', logs=content)

blog/views.py
"""
Author: Josh and Andrew
Description: This module defines a Flask blueprint for a blog feature. It includes routes and views for creating,
 displaying, and accessing recipes.
"""
import notifications
from blog.forms import RecipeForm, images, EditRecipeForm
from models import Post
from flask import Blueprint, render_template, url_for, send_from_directory
from app import db, app, requires_roles
from flask_login import login_required, current_user

blog_blueprint = Blueprint('blog', __name__, template_folder='templates')


# Send a file from within a directory using send_file.
@app.route("/images/images/<filename>")
def get_file(filename):
    return send_from_directory("images/images", filename)


# blog function for handling blog form inputs
@blog_blueprint.route('/blog', methods=['GET', 'POST'])
@login_required
@requires_roles('user', 'admin')
def blog():
    form = RecipeForm()
    if form.validate_on_submit():

        # receives image and saves to app default file path
        image_name = images.save(form.image.data)
        # gets url for image to save in the database
        image_url = url_for("get_file", filename=image_name)

        new_post = Post(user_id=current_user.id,
                        title=form.title.data,
                        recipe=form.recipe.data,
                        ingredients=form.ingredients.data,
                        image=image_url,
                        price=form.price.data)

        # add the new recipe to the database
        db.session.add(new_post)
        db.session.commit()

        # sends email notification of new blog post to all users signed up
        notifications.send_emails()

        return render_template('/blog/blog.html', form=form, file_url=image_url)

    return render_template('/blog/blog.html', form=form)


# gets all recipe posts from database and passes them to blog_home to display
@blog_blueprint.route('/blog_home', methods=['GET','POST'])
def blog_home():
    recipes = Post.query.all()
    order_by = "recent"
    if recipes:
        return render_template('blog/blog_home.html', recipes=recipes, order_by=order_by)

    return render_template('blog/blog_home.html')


# sorts recipe Posts by either amount of views or most recent and renders a new blog_home
@blog_blueprint.route('/order_recipes/<order>', methods=['GET','POST'])
def order_recipes(order):
    if order == "views":
        recipes = Post.query.order_by(Post.views.desc()).all()
        return render_template('blog/blog_home.html', recipes=recipes, order_by=order)
    if order == "recent":
        recipes = Post.query.order_by(Post.post_id.desc()).all()
        return render_template('blog/blog_home.html', recipes=recipes, order_by=order)


# gets the clicked on recipe from the database to display it fully in recipe.html
@blog_blueprint.route('/recipe/<recipe_id>', methods=['GET','POST'])
def recipe(recipe_id):
    recipe = Post.query.filter_by(post_id=recipe_id).first()
    if recipe:
        # increments views as it's been clicked on
        views = recipe.views
        views += 1
        recipe.views = views
        db.session.commit()
        return render_template('blog/recipe.html', recipe=recipe)

    return render_template('blog/recipe.html')


# deletes the recipe when delete is clicked, can only be done by admins or by the posts author
@login_required
@requires_roles('user', 'admin')
@blog_blueprint.route('/delete_recipe/<recipe_id>', methods=['GET','POST'])
def delete_recipe(recipe_id):
    recipe = Post.query.filter_by(post_id=recipe_id).first()
    if recipe:
        db.session.delete(recipe)
        db.session.commit()
        recipes = Post.query.all()

        return render_template('blog/blog_home.html', recipes=recipes)

    return render_template('blog/recipe.html')


# Allows authors or admins to edit their posts.
@login_required
@requires_roles('user', 'admin')
@blog_blueprint.route('/edit_recipe/<recipe_id>',  methods=['GET','POST'])
def edit_recipe(recipe_id):
    form = EditRecipeForm()
    # gets recipe to edit
    recipe = Post.query.filter_by(post_id=recipe_id).first()

    # if statements allow users to edit as much or as little as they want
    if form.validate_on_submit():
        if form.image.data:
            image_name = images.save(form.image.data)
            image_url = url_for("get_file", filename=image_name)
            recipe.image = image_url

        if form.title.data:
            recipe.title = form.title.data

        if form.recipe.data:
            recipe.recipe = form.recipe.data

        if form.ingredients.data:
            recipe.ingredients = form.ingredients.data

        if form.price.data:
            recipe.price = form.price.data

        db.session.commit()

        return render_template('blog/recipe.html', recipe=recipe)

    if recipe:
        return render_template('blog/edit_recipe.html', recipe=recipe, form=form)

    return render_template('blog/blog_home.html')

main/views.py
"""
Author: Shaikha Almajed
Description: This module contains the main blueprint for a Flask application.
"""
from flask import Blueprint, render_template

main_blueprint = Blueprint('main', __name__, template_folder='templates')


@main_blueprint.route('/')
def index():
    return render_template('main/index.html')

users/views.py
"""
Author: Shaikha + Vilius
Description: This module defines Flask routes for user registration, login, logout, profile, and settings.
 It also includes form validation, user authentication, and logging events.
"""
import bcrypt
from flask import Blueprint, render_template, redirect, url_for, flash, session, Markup, request
from app import db, requires_roles
from models import User
from users.forms import RegisterForm, LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from datetime import datetime
import logging


users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash('Email address already exists')
            return render_template('users/register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        notifications=form.notifications.data,
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # Logging an event for user registration
        logging.warning('SECURITY - User registration [%s, %s]',
                        form.email.data, request.remote_addr)

        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    # checking if the key-value pair is in the session, and adding it if not
    if not session.get('attempts'):
        # counting authentication attempts
        session['attempts'] = 0

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # check if user exists, password is correct and one-time password is correct
        if not user or not bcrypt.checkpw(form.password.data.encode('utf-8'), user.password):
            session['attempts'] += 1

            # Logging an event for user invalid login
            logging.warning('SECURITY - Invalid log in [%s, %s]',
                            form.email.data, request.remote_addr)

            # limiting login attempts to only 4 attempts
            if session.get('attempts') >= 4:
                flash(Markup('Number of incorrect login attempts exceeded. '
                             'please click <a href="/reset">here</a> to reset.'))
                return render_template('users/login.html')
            flash('please check your details,{} login attempts remaining'
                  .format(4 - session.get('attempts')))
            return render_template('users/login.html', form=form)

        # if user exists and passwords are correct, logs in user
        login_user(user)

        # Logging an event for user login
        logging.warning('SECURITY - Log in [%s, %s, %s]',
                        current_user.id, current_user.email,
                        request.remote_addr)

        # # update last login and current login time
        user.last_login = user.current_login
        user.current_login = datetime.now()
        db.session.add(user)
        db.session.commit()

        # if statement to redirect user to correct page based on their role
        if current_user.role == 'user':
            return redirect(url_for('blog.blog_home'))
        else:
            return redirect(url_for('admin.admin'))
    return render_template('users/login.html', form=form)


@users_blueprint.route('/reset')
def reset():
    session['attempts'] = 0
    return redirect(url_for('users.login'))


# view user logout
@users_blueprint.route('/logout')
@login_required
@requires_roles('user', 'admin')
def logout():
    # Logging an event for user logout
    logging.warning('SECURITY - Log out [%s, %s, %s]',
                    current_user.id, current_user.email, request.remote_addr)
    logout_user()
    return redirect(url_for('main.index'))


# view user account
@users_blueprint.route('/profile')
@login_required
@requires_roles('user', 'admin')
def profile():
    return render_template('users/profile.html',
                           acc_no=current_user.id,
                           email=current_user.email,
                           firstname=current_user.firstname,
                           lastname=current_user.lastname,
                           phone=current_user.phone)

@users_blueprint.route('/settings')
def settings():
    return render_template('users/settings.html')

templates/base.html
<!--Authors: Vilius + Josh + Andrew + Shaikha -->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/register-login.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/aboutus.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/profile.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/locator.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">

    </head>
    <body>
            <nav class="navbar">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-start">
                            <a class="navbar-item">
                                <img src="{{ url_for('static', filename='images/LogoText.png') }}" alt="Website Logo">
                            </a>
                            {% if current_user.is_anonymous %}
                            <a href="{{ url_for('main.index') }}"class="navbar-item"><i class="fas fa-home"></i>
                                Home
                            </a>
                            {% endif %}
                            <a href="{{ url_for('blog.blog_home') }}" class="navbar-item"><i class="fas fa-book"></i>
                                Recipes
                            </a>
                            <a href="{{ url_for('locator.locator') }}" class="navbar-item"><i class="fas fa-map-marker-alt"></i>
                                Find Food
                            </a>
                            <a href="{{ url_for('Aboutus.Aboutus') }}" class="navbar-item"><i class="fas fa-info-circle"></i>
                                About us
                            </a>
                            {% if current_user.is_authenticated and current_user.role == 'admin' %}
                            <a href="{{ url_for('admin.admin') }}" class="navbar-item"><i class="fas fa-user-shield"></i>
                                Admin
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('users.settings') }}" class="navbar-item"><i class="fas fa-cog"></i>
                                Settings
                            </a>
                            {% endif %}
                        </div>
                    </div>

            </nav>
        <div class="hero-body is-fluid">
            <div class="container has-text-centered is-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <footer class="footer custom-footer">
            <div class="content has-text-centered">
                <p>Contact us at: <a href="mailto:hungerhelphelp@gmail.com">hungerhelphelp@gmail.com</a></p>
            </div>
        </footer>
    </body>
</html>