users/forms.py
"""
Author: Shaikha Almajed
Description: This code defines Flask forms for user registration and login
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, ValidationError, EqualTo, Length
import re
from flask_wtf import RecaptchaField


# A function that excludes some special characters
def character_check(form, field):
    excluded_chars = "* ? ! ' ^ + % & / ( ) = } ] [ { $ # @ < >"
    for char in field.data:
        if char in excluded_chars:
            raise ValidationError(f"Character {char} is not allowed.")


# A regex function that specifies that digits must be in the form: XXXX-XXX-XXXX
def validate_phone(form, phone):
    p = re.compile(r"\d{4}[-]\d{3}[-]\d{4}$")
    if not p.match(phone.data):
        raise ValidationError("Invalid phone number, must be in the form XXXX-XXX-XXXX")


# A regex function that specifies that it must contain at least 1 digit and at least
# 1 lowercase word character and at least 1 uppercase word character and at least 1 special character
def validate_pass(form, password):
    p = re.compile(r"(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*\W+)")
    if not p.match(password.data):
        raise ValidationError("Must contain at least 1 digit, 1 lowercase word character, "
                              "1 uppercase word character and 1 special character ")


class RegisterForm(FlaskForm):
    email = StringField(validators=[DataRequired(),
                                    Email()])
    firstname = StringField(validators=[DataRequired(),
                                        character_check])
    lastname = StringField(validators=[DataRequired(),
                                       character_check])
    phone = StringField(validators=[DataRequired(),
                                    validate_phone])
    password = PasswordField(validators=[DataRequired(),
                                         Length(min=6, max=12),
                                         validate_pass])
    confirm_password = PasswordField(validators=[DataRequired(),
                                                 EqualTo('password', message='Both password fields must be equal!')])
    notifications = BooleanField(label='Receive notifications')

    submit = SubmitField()


class LoginForm(FlaskForm):
    email = StringField(validators=[DataRequired()])
    password = PasswordField(validators=[DataRequired()])
    recaptcha = RecaptchaField()
    submit = SubmitField()

users/views.py
"""
Author: Shaikha + Vilius
Description: This module defines Flask routes for user registration, login, logout, profile, and settings.
 It also includes form validation, user authentication, and logging events.
"""
import bcrypt
from flask import Blueprint, render_template, redirect, url_for, flash, session, Markup, request
from app import db, requires_roles
from models import User
from users.forms import RegisterForm, LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from datetime import datetime
import logging


users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash('Email address already exists')
            return render_template('users/register.html', form=form)

        # create a new user with the form data
        new_user = User(email=form.email.data,
                        firstname=form.firstname.data,
                        lastname=form.lastname.data,
                        phone=form.phone.data,
                        password=form.password.data,
                        notifications=form.notifications.data,
                        role='user')

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        # Logging an event for user registration
        logging.warning('SECURITY - User registration [%s, %s]',
                        form.email.data, request.remote_addr)

        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    # checking if the key-value pair is in the session, and adding it if not
    if not session.get('attempts'):
        # counting authentication attempts
        session['attempts'] = 0

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # check if user exists, password is correct and one-time password is correct
        if not user or not bcrypt.checkpw(form.password.data.encode('utf-8'), user.password):
            session['attempts'] += 1

            # Logging an event for user invalid login
            logging.warning('SECURITY - Invalid log in [%s, %s]',
                            form.email.data, request.remote_addr)

            # limiting login attempts to only 4 attempts
            if session.get('attempts') >= 4:
                flash(Markup('Number of incorrect login attempts exceeded. '
                             'please click <a href="/reset">here</a> to reset.'))
                return render_template('users/login.html')
            flash('please check your details,{} login attempts remaining'
                  .format(4 - session.get('attempts')))
            return render_template('users/login.html', form=form)

        # if user exists and passwords are correct, logs in user
        login_user(user)

        # Logging an event for user login
        logging.warning('SECURITY - Log in [%s, %s, %s]',
                        current_user.id, current_user.email,
                        request.remote_addr)

        # # update last login and current login time
        user.last_login = user.current_login
        user.current_login = datetime.now()
        db.session.add(user)
        db.session.commit()

        # if statement to redirect user to correct page based on their role
        if current_user.role == 'user':
            return redirect(url_for('blog.blog_home'))
        else:
            return redirect(url_for('admin.admin'))
    return render_template('users/login.html', form=form)


@users_blueprint.route('/reset')
def reset():
    session['attempts'] = 0
    return redirect(url_for('users.login'))


# view user logout
@users_blueprint.route('/logout')
@login_required
@requires_roles('user', 'admin')
def logout():
    # Logging an event for user logout
    logging.warning('SECURITY - Log out [%s, %s, %s]',
                    current_user.id, current_user.email, request.remote_addr)
    logout_user()
    return redirect(url_for('main.index'))


# view user account
@users_blueprint.route('/profile')
@login_required
@requires_roles('user', 'admin')
def profile():
    return render_template('users/profile.html',
                           acc_no=current_user.id,
                           email=current_user.email,
                           firstname=current_user.firstname,
                           lastname=current_user.lastname,
                           phone=current_user.phone)

@users_blueprint.route('/settings')
def settings():
    return render_template('users/settings.html')

templates/users/login.html
<!--Authors: Vilius + Shaikha -->

{% extends "base.html" %}

{% block content %}

    <div class="column is-5 is-offset-4">
        <div class="container-register-login">
            <div class="container-image">
                <img class="background-img" src="{{ url_for('static', filename='images/greenbackground.jpg') }}">
            </div>
            <div class="container-form">
                {% if form %}
                    <form method="POST" class="form">
                        <h3 class="title">Login</h3>
                        <div class="form-field">
                            {{ form.csrf_token }}
                            <div class="control">
                                {{ form.email(class="input", placeholder="Email") }}
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-field">
                            <div class="control">
                                {{ form.password(class="input", placeholder="Password") }}
                            </div>
                        </div>
                        <div class="form-field">
                            {{ form.recaptcha }}
                        </div>
                        <div class="form-field">
                            {{ form.submit(class="button is-success is-centered") }}
                        </div>

                {% endif %}
                {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                <div class="notification is-danger">
                                        {{ messages[0] }}
                                </div>
                            {% endif %}
                        {% endwith %}
                <div class="form-field">
                    Don't have an account? <a href="{{ url_for('users.register') }}">Register here</a>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
<!--Author: Shaikha -->

{% extends "base.html" %}

{% block content %}
<div class="column is-6 is-offset-3">
    <div class="container-profile">
        <header class="intro-header" style="background-image: url('static/images/simple-green.jpg');">
            <div class="box">
                <h1 class="title is-1">Your Profile</h1>
                <table class="profile-table">
                    <tbody>
                        <tr>
                            <th>Account No.</th>
                            <td>{{ current_user.id }}</td>
                        </tr>
                        <tr>
                            <th>Email</th>
                            <td>{{ current_user.email }}</td>
                        </tr>
                        <tr>
                            <th>First Name</th>
                            <td>{{ current_user.firstname }}</td>
                        </tr>
                        <tr>
                            <th>Last Name</th>
                            <td>{{ current_user.lastname }}</td>
                        </tr>
                        <tr>
                            <th>Phone No.</th>
                            <td>{{ current_user.phone }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </header>
    </div>
</div>
{% endblock %}

templates/users/register.html
<!--Authors: Vilius + Shaikha -->

{% extends "base.html" %}

{% block content %}
    <div class="column is-5 is-offset-4">
        <div class="container-register-login">
            <div class="container-image" >
                <img class="background-img" src="{{ url_for('static', filename='images/greenbackground.jpg') }}">
            </div>
            <div class="container-form">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="notification is-danger">
                            {{ messages[0] }}. Go to <a href="{{ url_for('users.login') }}">login page</a>.
                        </div>
                    {% endif %}
                {% endwith %}
                <form method="POST" class="form">
                    <h3 class="title">Register</h3>
                    <div>
                        {{ form.csrf_token }}
                        <div class="form-field">
                            {{ form.email(class="input", placeholder="Email") }}
                            {% for error in form.email.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div>
                        <div class="form-field">
                            {{ form.firstname(class="input", placeholder="First Name") }}
                            {% for error in form.firstname.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div>
                        <div class="form-field">
                            {{ form.lastname(class="input", placeholder="Last Name") }}
                            {% for error in form.lastname.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div>
                        <div class="form-field">
                            {{ form.phone(class="input", placeholder="Phone") }}
                            {% for error in form.phone.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div>
                        <div class="form-field">
                            {{ form.password(class="input", placeholder="Password") }}
                            {% for error in form.password.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div>
                        <div class="form-field">
                            {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                            {% for error in form.confirm_password.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                     <div>
                        <div class="form-field">
                            {{ form.notifications(class="checkbox", placeholder="Send Email Notifications") }}
                            I agree to receive post notifications for the blog
                            {% for error in form.confirm_password.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-field">
                        {{ form.submit(class="button is-success is-centered") }}
                    </div>
                    <div class="form-field">
                        Already have an account? <a href="{{ url_for('users.login') }}"> Login here </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

{% endblock %}

templates/users/settings.html
<!--Author: Shaikha -->

{% extends "base.html" %}

{% block content %}

        {% if current_user.is_authenticated %}
        <a href="{{ url_for('users.profile') }}" class="navbar-item"><i class="fas fa-user"></i>
            Profile
        </a>
        <a href="{{ url_for('users.logout') }}" class="navbar-item"><i class="fas fa-sign-out-alt"></i>
            Log out
        </a>
        {% endif %}

{% endblock %}